# Generated by Django 5.2.3 on 2025-06-12 00:59

import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('imagem', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=75, null=True)),
                ('uf', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=75, null=True)),
                ('uf', models.CharField(blank=True, max_length=5, null=True)),
                ('regiao', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('identificador_nav', models.CharField(default='', max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='EM ABERTO', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proteina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('imagem', ckeditor.fields.RichTextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=70)),
                ('tipo_cadastro', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateTimeField()),
                ('dia', models.CharField(blank=True, max_length=2, null=True)),
                ('mes', models.CharField(blank=True, max_length=2, null=True)),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', ckeditor_uploader.fields.RichTextUploadingField()),
                ('icone', ckeditor_uploader.fields.RichTextUploadingField()),
                ('nome', models.CharField(max_length=255)),
                ('subtitulo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cnpj', models.CharField(max_length=100)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('fone', models.CharField(blank=True, max_length=70, null=True)),
                ('whatsapp', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=255)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=100)),
                ('senha_email', models.CharField(max_length=255)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(blank=True, max_length=70, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdelivery.cidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdelivery.estado')),
            ],
            options={
                'verbose_name': 'Dado',
                'verbose_name_plural': 'Dados',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='qdelivery.estado'),
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('capa', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Q', 'Quentinha'), ('B', 'Bebidas')], max_length=1)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinas', models.JSONField(default=list)),
                ('acompanhamentos', models.JSONField(default=list)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='qdelivery.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdelivery.produtos')),
            ],
        ),
    ]
