# Generated by Django 5.0.6 on 2024-07-25 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=75, null=True)),
                ('uf', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=75, null=True)),
                ('uf', models.CharField(blank=True, max_length=5, null=True)),
                ('regiao', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=70)),
                ('tipo_cadastro', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateTimeField()),
                ('dia', models.CharField(blank=True, max_length=2, null=True)),
                ('mes', models.CharField(blank=True, max_length=2, null=True)),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=255)),
                ('icone', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cnpj', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('fone', models.CharField(blank=True, max_length=70, null=True)),
                ('whatsapp', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=255)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=100)),
                ('senha_email', models.CharField(max_length=255)),
                ('usuario', models.IntegerField()),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(blank=True, max_length=70, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdelivery.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdelivery.estado')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='qdelivery.estado'),
        ),
    ]
