# Generated by Django 5.0.7 on 2024-07-25 23:43

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='descricao',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='dados',
            name='icone',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
