# Generated by Django 5.0.7 on 2024-07-26 00:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0002_alter_dados_descricao_alter_dados_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='logo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
