# Generated by Django 5.0.7 on 2024-07-26 00:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0003_alter_dados_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='subtitulo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
