# Generated by Django 5.0.7 on 2024-07-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0006_produtos_decricao_produtos_valor_alter_dados_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='decricao',
            new_name='descricao',
        ),
    ]
