# Generated by Django 5.0.6 on 2024-07-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0007_rename_decricao_produtos_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='valor_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
