# Generated by Django 5.0.6 on 2024-07-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0008_produtos_valor_promo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados',
            options={'verbose_name': 'Dado', 'verbose_name_plural': 'Dados'},
        ),
    ]
