# Generated by Django 5.0.7 on 2024-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0010_alter_produtos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Q', 'Quentinha'), ('B', 'Bebidas')], max_length=1, null=True),
        ),
    ]
