# Generated by Django 5.0.7 on 2024-07-28 15:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0012_alter_produtos_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='capa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
