# Generated by Django 5.0.7 on 2024-07-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0013_alter_produtos_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name': 'Dado', 'verbose_name_plural': 'Dados'},
        ),
    ]
