# Generated by Django 5.0.7 on 2024-07-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0014_alter_produtos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
