# Generated by Django 5.0.7 on 2024-08-01 21:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0017_pedido_itempedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('imagem', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
