# Generated by Django 5.0.7 on 2024-08-02 00:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0018_acompanhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamento',
            name='imagem',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
