# Generated by Django 5.0.7 on 2024-08-02 00:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0019_alter_acompanhamento_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='acompanhamento',
            name='imagem',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
