# Generated by Django 5.0.7 on 2024-08-02 00:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0020_produtos_ativo_alter_acompanhamento_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proteinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('imagem', ckeditor.fields.RichTextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
