# Generated by Django 5.0.7 on 2024-08-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0021_proteinar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proteinar',
            new_name='Proteina',
        ),
    ]
