# Generated by Django 5.0.6 on 2024-08-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0023_bairro_pedido_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='EM ABERTO', max_length=50),
        ),
    ]
