# Generated by Django 5.0.6 on 2024-10-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0024_pedido_bairro_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='identificador_nav',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
