# Generated by Django 5.0.6 on 2024-08-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0025_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
