# Generated by Django 5.0.6 on 2024-10-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0025_pedido_identificador_nav_alter_pedido_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
