# Generated by Django 5.0.6 on 2024-10-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0026_alter_pedido_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='acompanhamentos',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='proteinas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
