# Generated by Django 5.0.6 on 2024-08-28 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0027_cliente_remove_carrinho_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdelivery.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qdelivery.cliente'),
        ),
    ]
