# Generated by Django 5.0.6 on 2024-08-28 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0028_alter_carrinho_cliente_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qdelivery.cliente'),
        ),
    ]
