# Generated by Django 5.0.6 on 2024-08-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0030_alter_cliente_nome_alter_cliente_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='identificado',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='identificador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='identificador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
