# Generated by Django 5.0.6 on 2024-09-05 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdelivery', '0031_remove_cliente_identificado_carrinho_identificador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='produto_id',
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='acompanhamentos',
            field=models.ManyToManyField(to='qdelivery.acompanhamento'),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qdelivery.produtos'),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='proteinas',
            field=models.ManyToManyField(to='qdelivery.proteina'),
        ),
    ]
