# Generated by Django 5.2.3 on 2025-06-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('status', models.CharField(default='ATIVO', max_length=10)),
            ],
            options={
                'db_table': 'qd_ctt_wts',
            },
        ),
    ]
