# Generated by Django 5.2.3 on 2025-06-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
    ]
